PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX rbo: <http://uniandes.edu.co/wsproject2026/vocab/ontology#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 



SELECT ?artist ?track ?title
WHERE {
    ?artist a res:Artist ;
            rbo:origin res:Country_US .
    ?track a res:Track .
    ?track rbo:sungBy ?artist .
    ?track rbo:title ?title .
}