PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX rbo: <http://uniandes.edu.co/wsproject2026/vocab/ontology#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 



SELECT ?track ?similarTrack
WHERE {
    ?artist a res:Artist .
    ?track a res:Track ;
            rbo:sungBy ?artist ;
            rbo:hasSimilarity ?nb .
    ?nb rbo:similarTrack ?similarTrack ;
        rbo:similarityScore ?score .

    FILTER(?score > 0.5)
}