PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX rbo: <http://uniandes.edu.co/wsproject2026/vocab/ontology#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX res: <http://uniandes.edu.co/wsproject2026/vocab/lit#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 



SELECT (COUNT(DISTINCT ?track) AS ?totalTracks)
WHERE {
    ?track rbo:hasSimilarity ?nb .
    ?nb rbo:similarityScore 1 .
}